modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ratcopter" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Glumbis" #mandatory
logoFile="examplemod.png" #optional
credits="Virtualhel" #optional
authors="Coda" #optional
description='''
Glumbis lets you pick up cats in socks for easy transport!'''
[[dependencies.glumbis]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.glumbis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
